config/routes.rb
Rails.application.routes.draw do
  resources :priorities
  root to: 'sessions#new'
  get 'sessions/new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  resources :document_types
  resources :plans
  resources :admins
  resources :items

  resources :players do
    collection do
      get 'active'
      get 'inactive'
    end

    member do
      put 'activate'
      put 'deactivate'
      get 'status'
      get 'items'
    end
  end

  namespace :documents do
    resources :pendings do
      get 'index'
      get 'pending', to: :edit
      put 'pending', to: :update, as: 'edit_pending'
    end
  end

  resources :documents

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AE Academy</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->
  </head>
  <body>
    <% if logged_in? %>
    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <nav>
          <ul class="nav navbar-nav navbar-left">
            <% if current_user.is_a?(Admin) %>
              <li class='navbar-brand'><%= link_to "AE ACADEMY", active_players_path %></li>
              <li><%= link_to "Active Players", active_players_path %></li>              <li><%= link_to "Inactive Players", inactive_players_path %></li>
              <li><%= link_to "Register Player", new_player_path %></li>
              <li><%= link_to "Plans", plans_path %></li>
            <% elsif current_user.is_a?(Player) %>
              <li class='navbar-brand'><%= link_to "AE ACADEMY", status_player_path(current_user) %></li>
              <li><%= link_to "Status Page", status_player_path(current_user) %></li>
              <li><%= link_to "My Profile", edit_player_path(current_user) %></li>
              <li><%= link_to "Tell My Story", player_path(current_user.id) %></li>
              <li><%= link_to "Profile Summary", player_path(current_user.id) %></li>
              <li><%= link_to "My Priorities", new_priority_path %></li>
            <% end %>
            <li><%= link_to "Log out", logout_path, method: :delete %></li>
          </ul>
        </nav>
      </div>
    </header>
    <% end %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>